### ISSUE TITLE
TBC patch 2.5.3

### ISSUE THREAD

**Issue by kriminy** [neotron/WoW-BulkMail-Inbox#7]
The new patch today seems to have broken the add-on or one of the libraries it uses. It doesn't load when visiting the mailbox, and there's a LUA error which I've included below:

Message: ...dOns\BulkMail2Inbox\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
Time: Tue Jan 18 21:24:11 2022
Count: 4
Stack: ...dOns\BulkMail2Inbox\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\BulkMail2Inbox\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:543: in function <...dOns\BulkMail2Inbox\Libs\LibQTip-1.0\LibQTip-1.0.lua:539>
[string "@Interface\AddOns\BulkMail2Inbox\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:132: in function `Acquire'
[string "@Interface\AddOns\BulkMail2Inbox\BulkMailInbox.lua"]:956: in function `ShowInboxGUI'
[string "@Interface\AddOns\BulkMail2Inbox\BulkMailInbox.lua"]:342: in function `?'
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

Locals: <none>

**Comment by neotron** [comment]
LibQTip is a third party addon. I have repackaged it with the new toc and new dependencies will be uses which should fix the issue.
